version: "2.2"
services:
  reverse-proxy:
    image: nginx:latest
    container_name: image-proxy-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ~/generated-images:/opt/gen-images
    ports:
      - "4044:80"
      - "443:443"
  redis-server:
    image: redis:latest
    container_name: image-gen-redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - /tmp/redis-data:/data